server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices1
    username: root
    password: Official@17301
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import:
      - configserver:http://localhost:8085

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Because of upper configuration now we can import common configurations from the server

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-75072506.okta.com/oauth2/default
    audience: api://default

